/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verify_email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/totp/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm_totp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/totp/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start_totp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start_recovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/recovery/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["complete_recovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["current_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_events"];
        put?: never;
        post: operations["create_event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_challenges"];
        put?: never;
        post: operations["create_challenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/challenges/{challenge_id}/hints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_hints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/challenges/{challenge_id}/hints/{hint_id}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unlock_hint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/challenges/{challenge_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submit_answer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/challenges/{challenge_id}/survey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submit_survey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/challenges/{challenge_id}/survey-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["survey_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/challenges/{challenge_id}/writeup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_writeup"];
        put: operations["save_writeup"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/manual-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manual_review_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/manual-reviews/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["review_manual_submission"];
        trace?: never;
    };
    "/api/v1/events/{event_id}/scoreboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["scoreboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/scoreboard-controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_scoreboard_controls"];
        trace?: never;
    };
    "/api/v1/events/{event_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_event_state"];
        trace?: never;
    };
    "/api/v1/events/{event_id}/writeups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_writeups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/writeups/{writeup_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["review_writeup"];
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["setup_status"];
        put?: never;
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_teams"];
        put?: never;
        post: operations["create_team"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["join_team"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/captain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transfer_captain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Author-submitted answer rule. Exact plaintext is digested before storage. */
        AnswerInput: {
            case_insensitive: boolean;
            /** @enum {string} */
            kind: "exact";
            value: string;
        } | {
            case_insensitive: boolean;
            /** @enum {string} */
            kind: "regex";
            pattern: string;
        } | {
            /** @enum {string} */
            kind: "choice";
            value: string;
        } | {
            /** @enum {string} */
            kind: "dynamic";
        } | {
            /** @enum {string} */
            kind: "manual";
        };
        /** @description Challenge behavior input. */
        ChallengeKindInput: {
            /** @enum {string} */
            type: "static_flag";
        } | {
            choices: string[];
            /** @enum {string} */
            type: "multiple_choice";
        } | {
            template: string;
            /** @enum {string} */
            type: "dynamic_instance";
        } | {
            /** @enum {string} */
            type: "file_backed";
        } | {
            connection: string;
            /** @enum {string} */
            type: "remote_service";
        } | {
            /** @enum {string} */
            type: "manual_verification";
        } | {
            kind: string;
            plugin: string;
            /** @enum {string} */
            type: "plugin";
        };
        /** @description Player-safe challenge response. Answer rules never appear here. */
        ChallengeResponse: {
            /** @description Category. */
            category: string;
            /** @description Markdown description. */
            description: string;
            /**
             * Format: uuid
             * @description Event ID.
             */
            event_id: string;
            /**
             * Format: uuid
             * @description ID.
             */
            id: string;
            /** @description Behavior schema. */
            kind: components["schemas"]["ChallengeKindInput"];
            /**
             * Format: int32
             * @description Attempt limit.
             */
            max_attempts?: number | null;
            /** @description Name. */
            name: string;
            /**
             * Format: int32
             * @description Board position.
             */
            position: number;
            /** @description Scoring schema. */
            scoring: components["schemas"]["ScoringInput"];
            /** @description Whether the authenticated competitor has already solved it. */
            solved: boolean;
            /** @description Lifecycle. */
            state: string;
            /** @description Survey schema. */
            survey: components["schemas"]["SurveyInput"][];
            /** @description Tags. */
            tags: string[];
            /** @description Visibility schema. */
            visibility: components["schemas"]["VisibilityInput"];
            /** @description Writeups enabled. */
            writeups_enabled: boolean;
        };
        /**
         * @description Challenge lifecycle input.
         * @enum {string}
         */
        ChallengeStateInput: "draft" | "testing" | "scheduled" | "published" | "hidden" | "archived";
        /** @description New challenge aggregate. */
        CreateChallengeRequest: {
            /** @description Accepted rules. */
            answers: components["schemas"]["AnswerInput"][];
            /** @description Board category. */
            category: string;
            /** @description Markdown body. */
            description: string;
            /** @description Hints. */
            hints: components["schemas"]["HintInput"][];
            /** @description Behavior. */
            kind: components["schemas"]["ChallengeKindInput"];
            /**
             * Format: int32
             * @description Optional failure ceiling.
             */
            max_attempts?: number | null;
            /** @description Name. */
            name: string;
            /**
             * Format: int32
             * @description Board order.
             */
            position: number;
            /** @description Score policy. */
            scoring: components["schemas"]["ScoringInput"];
            /** @description Lifecycle. */
            state: components["schemas"]["ChallengeStateInput"];
            /** @description Survey schema. */
            survey: components["schemas"]["SurveyInput"][];
            /** @description Search and grouping tags. */
            tags: string[];
            /** @description Visibility rules. */
            visibility: components["schemas"]["VisibilityInput"];
            /** @description Permit writeup submission. */
            writeups_enabled: boolean;
        };
        /** @description New event document. */
        CreateEventRequest: {
            /** @description Markdown overview. */
            description: string;
            /**
             * Format: date-time
             * @description Optional closing instant.
             */
            ends_at?: string | null;
            /** @description At least one enabled mode. */
            modes: components["schemas"]["ModeInput"][];
            /** @description Display name. */
            name: string;
            /** @description Scoring identity policy. */
            participation: components["schemas"]["ParticipationInput"];
            /** @description URL-safe key. */
            slug: string;
            /**
             * Format: date-time
             * @description Optional opening instant.
             */
            starts_at?: string | null;
            /** @description Initial lifecycle. */
            state: components["schemas"]["EventStateInput"];
            /**
             * Format: int32
             * @description Optional team size limit.
             */
            team_size_limit?: number | null;
        };
        /** @description New team input. */
        CreateTeamRequest: {
            /** @description Display name. */
            name: string;
        };
        /** @description One-time team creation response. The invite code is never retrievable later. */
        CreateTeamResponse: {
            /** @description Opaque invite code shown once. */
            invite_code: string;
            /** @description Created team. */
            team: components["schemas"]["TeamResponse"];
        };
        /** @description Machine-readable error response. */
        ErrorBody: {
            /** @description Stable error code. */
            code: string;
            /** @description Safe human-readable detail. */
            message: string;
        };
        /** @description Safe event response. */
        EventResponse: {
            /** @description Description. */
            description: string;
            /**
             * Format: date-time
             * @description End.
             */
            ends_at?: string | null;
            /**
             * Format: uuid
             * @description ID.
             */
            id: string;
            /** @description Modes. */
            modes: string[];
            /** @description Name. */
            name: string;
            /** @description Participation. */
            participation: string;
            /** @description Freeze state. */
            scoreboard_frozen: boolean;
            /** @description Hidden state. */
            scoreboard_hidden: boolean;
            /** @description Slug. */
            slug: string;
            /**
             * Format: date-time
             * @description Start.
             */
            starts_at?: string | null;
            /** @description Lifecycle. */
            state: string;
            /**
             * Format: int32
             * @description Team limit.
             */
            team_size_limit?: number | null;
        };
        /**
         * @description Event lifecycle input.
         * @enum {string}
         */
        EventStateInput: "draft" | "scheduled" | "live" | "paused" | "ended" | "archived";
        /** @description Health document. */
        HealthResponse: {
            /** @description Stable status. */
            status: string;
            /**
             * Format: int64
             * @description Process uptime in seconds.
             */
            uptime_seconds: number;
            /** @description Server version. */
            version: string;
        };
        /** @description Hint authoring input. */
        HintInput: {
            /** @description Markdown content. */
            content: string;
            /**
             * Format: int64
             * @description Point cost.
             */
            cost: number;
            /**
             * Format: int32
             * @description Stable positive key.
             */
            id: number;
        };
        /** @description Player-safe hint state. */
        HintResponse: {
            /** @description Content, present only after unlock. */
            content?: string | null;
            /**
             * Format: int64
             * @description One-time score cost.
             */
            cost: number;
            /**
             * Format: int32
             * @description Challenge-local identifier.
             */
            id: number;
            /** @description Current competitor unlock state. */
            unlocked: boolean;
        };
        /** @description Idempotent hint unlock receipt. */
        HintUnlockResponse: {
            /**
             * Format: int64
             * @description Score points charged by this request.
             */
            charged: number;
            /** @description Revealed hint. */
            hint: components["schemas"]["HintResponse"];
            /** @description True when no second charge was applied. */
            replayed: boolean;
        };
        /** @description Join-code input. */
        JoinTeamRequest: {
            /** @description Opaque code supplied by a captain. */
            invite_code: string;
        };
        /** @description Local login input. */
        LoginRequest: {
            /** @description Account email. */
            email: string;
            /** @description Six-digit TOTP or a single-use recovery code when MFA is enabled. */
            mfa_code?: string | null;
            /** @description Organization slug. */
            organization: string;
            /**
             * Format: password
             * @description Account password.
             */
            password: string;
        };
        /** @description Pending manual-verification evidence visible only to submission managers. */
        ManualReviewResponse: {
            /** @description Decrypted evidence, never persisted or logged as plaintext. */
            answer: string;
            /**
             * Format: uuid
             * @description Challenge identifier.
             */
            challenge_id: string;
            /** @description Challenge display name. */
            challenge_name: string;
            /**
             * Format: uuid
             * @description Competitor identifier.
             */
            competitor_id: string;
            /** @description `user` or `team`. */
            competitor_kind: string;
            /** @description Competitor display name. */
            competitor_name: string;
            /**
             * Format: uuid
             * @description Submission identifier.
             */
            id: string;
            /**
             * Format: date-time
             * @description Submission timestamp.
             */
            submitted_at: string;
        };
        /**
         * @description First-party game mode key.
         * @enum {string}
         */
        ModeInput: "jeopardy" | "koth" | "attack_defense" | "workshop";
        /**
         * @description Event scoring identity policy.
         * @enum {string}
         */
        ParticipationInput: "individual" | "team" | "hybrid";
        /** @description Readiness document. */
        ReadinessResponse: {
            /** @description PostgreSQL dependency state. */
            postgres: string;
            /** @description Stable status. */
            status: string;
        };
        /** @description Recovery codes are returned exactly once. */
        RecoveryCodesResponse: {
            /** @description Single-use codes. The operator must store these safely. */
            codes: string[];
        };
        /** @description Complete recovery with a new password. */
        RecoveryCompleteRequest: {
            /**
             * Format: password
             * @description Replacement password.
             */
            password: string;
            /** @description URL-safe one-time token. */
            token: string;
        };
        /** @description Begin recovery without revealing whether an identity exists. */
        RecoveryStartRequest: {
            /** @description Account email. */
            email: string;
            /** @description Organization slug. */
            organization: string;
        };
        /** @description Local self-registration input. */
        RegisterRequest: {
            /** @description Public display name. */
            display_name: string;
            /** @description Account email. */
            email: string;
            /** @description Organization slug to join. */
            organization: string;
            /**
             * Format: password
             * @description Account password (12–128 characters).
             */
            password: string;
        };
        /** @description Organizer manual-verification decision. */
        ReviewManualSubmissionRequest: {
            /** @description Accept and score the submission when true; otherwise discard it. */
            accepted: boolean;
            /** @description Optional reviewer note, up to 10,000 bytes. */
            note?: string | null;
        };
        /** @description Organizer writeup review input. */
        ReviewWriteupRequest: {
            /** @description Review feedback, required when requesting changes. */
            feedback?: string | null;
            /** @description Requested review state. */
            state: components["schemas"]["WriteupReviewStateInput"];
        };
        /** @description Player writeup draft or submission input. */
        SaveWriteupRequest: {
            /** @description Markdown body, up to 100,000 bytes. */
            body: string;
            /** @description Enter the organizer review queue after saving. */
            submit: boolean;
        };
        /** @description Scoreboard controls and ordered standings. */
        ScoreboardResponse: {
            /** @description Post-freeze entries are concealed from players. */
            frozen: boolean;
            /** @description Organizer has hidden the public board. */
            hidden: boolean;
            /** @description Ranked rows. */
            rows: components["schemas"]["ScoreboardRowResponse"][];
        };
        /** @description Ranked scoreboard row. */
        ScoreboardRowResponse: {
            /**
             * Format: uuid
             * @description Competitor identifier.
             */
            competitor_id: string;
            /** @description `user` or `team`. */
            competitor_kind: string;
            /** @description Public display name. */
            name: string;
            /** @description One-based public rank. */
            rank: number;
            /**
             * Format: date-time
             * @description Earliest-to-reach tie-break timestamp.
             */
            reached_at: string;
            /**
             * Format: int64
             * @description Visible score total.
             */
            score: number;
            /**
             * Format: int64
             * @description Accepted challenge solve count.
             */
            solves: number;
        };
        /** @description Scoring configuration. */
        ScoringInput: {
            /** @enum {string} */
            kind: "static";
            /** Format: int64 */
            points: number;
        } | {
            /** Format: int64 */
            decay: number;
            /** Format: int64 */
            initial: number;
            /** @enum {string} */
            kind: "dynamic";
            /** Format: int64 */
            minimum: number;
        } | {
            /** @enum {string} */
            kind: "plugin";
            plugin: string;
            strategy: string;
        };
        /** @description Session bootstrap used by the Svelte client. */
        SessionResponse: {
            /** @description CSRF value required in `x-csrf-token` on mutations. */
            csrf_token: string;
            /**
             * Format: date-time
             * @description Session expiry.
             */
            expires_at: string;
            /** @description Applicable permission keys. */
            permissions: string[];
            /** @description Current account. */
            user: components["schemas"]["UserResponse"];
        };
        /** @description One active login session. */
        SessionSummaryResponse: {
            /**
             * Format: date-time
             * @description Creation timestamp.
             */
            created_at: string;
            /** @description Whether this is the calling session. */
            current: boolean;
            /**
             * Format: date-time
             * @description Expiry timestamp.
             */
            expires_at: string;
            /**
             * Format: uuid
             * @description Session ID.
             */
            id: string;
            /**
             * Format: date-time
             * @description Last request timestamp.
             */
            last_seen_at: string;
        };
        /** @description First organization and administrator input. */
        SetupRequest: {
            /** @description Administrator display name. */
            display_name: string;
            /** @description Administrator email. */
            email: string;
            /** @description Organization display name. */
            organization_name: string;
            /** @description URL-safe organization key. */
            organization_slug: string;
            /**
             * Format: password
             * @description Administrator password (12–128 characters).
             */
            password: string;
        };
        /** @description First-run state. */
        SetupStatusResponse: {
            /** @description True when no user exists and setup can be completed. */
            required: boolean;
        };
        /** @description Safe immutable submission receipt. */
        SubmissionResponse: {
            /**
             * Format: int32
             * @description Remaining incorrect attempts when bounded.
             */
            attempts_remaining?: number | null;
            /**
             * Format: int64
             * @description Total solve and bonus points awarded.
             */
            awarded_points: number;
            /**
             * Format: uuid
             * @description Challenge identifier.
             */
            challenge_id: string;
            /** @description First accepted solve marker. */
            first_blood: boolean;
            /**
             * Format: uuid
             * @description Submission identifier.
             */
            id: string;
            /** @description `correct`, `incorrect`, or `pending`. */
            outcome: string;
            /** @description True when an earlier response was replayed by idempotency key. */
            replayed: boolean;
            /**
             * Format: date-time
             * @description Server receipt time.
             */
            submitted_at: string;
        };
        /** @description Idempotent answer submission. */
        SubmitAnswerRequest: {
            /** @description Flag, regular-expression candidate, or selected choice. */
            answer: string;
            /**
             * Format: uuid
             * @description Client-generated UUID reused for safe retries.
             */
            idempotency_key: string;
        };
        /** @description Validated post-solve survey submission. */
        SubmitSurveyRequest: {
            /** @description Integer answers keyed by authored question key. */
            answers: {
                [key: string]: number;
            };
        };
        /** @description Post-solve survey item. */
        SurveyInput: {
            /** @description Stable key. */
            key: string;
            /** @description Prompt. */
            prompt: string;
            /** @description Optional inclusive integer bounds. */
            range?: [
                number,
                number
            ] | null;
            /** @description Required answer. */
            required: boolean;
        };
        /** @description Aggregate statistics for one survey question. */
        SurveyQuestionSummaryResponse: {
            /**
             * Format: double
             * @description Arithmetic mean.
             */
            average?: number | null;
            /** @description Authored key. */
            key: string;
            /**
             * Format: int32
             * @description Highest response.
             */
            maximum?: number | null;
            /**
             * Format: int32
             * @description Lowest response.
             */
            minimum?: number | null;
            /** @description Authored prompt. */
            prompt: string;
            /** @description Responses containing this key. */
            responses: number;
        };
        /** @description Stable survey receipt. */
        SurveyResponse: {
            /** @description Validated answers. */
            answers: {
                [key: string]: number;
            };
            /**
             * Format: uuid
             * @description Challenge identifier.
             */
            challenge_id: string;
            /**
             * Format: uuid
             * @description Response identifier.
             */
            id: string;
            /**
             * Format: date-time
             * @description Last submission timestamp.
             */
            submitted_at: string;
        };
        /** @description Organizer-safe aggregate survey analytics. */
        SurveySummaryResponse: {
            /** @description Per-question statistics. */
            questions: components["schemas"]["SurveyQuestionSummaryResponse"][];
            /** @description Total competitor responses. */
            response_count: number;
        };
        /** @description Team member projection. */
        TeamMemberResponse: {
            /** @description Captain authority. */
            captain: boolean;
            /** @description Public display name. */
            display_name: string;
            /**
             * Format: date-time
             * @description Join instant.
             */
            joined_at: string;
            /**
             * Format: uuid
             * @description User ID.
             */
            user_id: string;
        };
        /** @description Team projection without invite secrets. */
        TeamResponse: {
            /**
             * Format: date-time
             * @description Creation instant.
             */
            created_at: string;
            /**
             * Format: uuid
             * @description Team ID.
             */
            id: string;
            /** @description Current members. */
            members: components["schemas"]["TeamMemberResponse"][];
            /** @description Display name. */
            name: string;
        };
        /** @description One opaque token input. */
        TokenRequest: {
            /** @description URL-safe one-time token. */
            token: string;
        };
        /** @description TOTP setup proof. */
        TotpConfirmRequest: {
            /** @description Current six-digit authenticator code. */
            code: string;
        };
        /** @description TOTP enrollment data for an authenticator application. */
        TotpEnrollmentResponse: {
            /** @description Standard `otpauth://` provisioning URI. */
            provisioning_uri: string;
            /** @description Base32 secret for manual entry. */
            secret: string;
        };
        /** @description Captain transfer input. */
        TransferCaptainRequest: {
            /**
             * Format: uuid
             * @description Existing member receiving captain authority.
             */
            user_id: string;
        };
        /** @description Organizer event lifecycle mutation. */
        UpdateEventStateRequest: {
            /** @description Requested lifecycle state. */
            state: components["schemas"]["EventStateInput"];
        };
        /** @description Organizer scoreboard control mutation. */
        UpdateScoreboardControlsRequest: {
            /** @description Conceal new score entries while preserving the last public snapshot. */
            frozen: boolean;
            /** @description Conceal the entire public scoreboard. */
            hidden: boolean;
        };
        /** @description Safe account projection. */
        UserResponse: {
            /** @description Display name. */
            display_name: string;
            /** @description Normalized email. */
            email: string;
            /** @description Email ownership state. */
            email_verified: boolean;
            /**
             * Format: uuid
             * @description User ID.
             */
            id: string;
            /**
             * Format: uuid
             * @description Organization ID.
             */
            organization_id: string;
        };
        /** @description Visibility window, division targeting, and unlock graph. */
        VisibilityInput: {
            /** @description Empty means every division. */
            division_ids: string[];
            /** @description All must be solved. */
            prerequisites: string[];
            /**
             * Format: date-time
             * @description Earliest visibility.
             */
            visible_from?: string | null;
            /**
             * Format: date-time
             * @description Exclusive hide instant.
             */
            visible_until?: string | null;
        };
        /** @description Player and organizer writeup projection. */
        WriteupResponse: {
            /** @description Markdown body. */
            body: string;
            /**
             * Format: uuid
             * @description Challenge identifier.
             */
            challenge_id: string;
            /** @description Challenge display name. */
            challenge_name: string;
            /**
             * Format: uuid
             * @description Competitor identifier.
             */
            competitor_id: string;
            /** @description `user` or `team`. */
            competitor_kind: string;
            /** @description Competitor display name. */
            competitor_name: string;
            /**
             * Format: date-time
             * @description Creation timestamp.
             */
            created_at: string;
            /** @description Organizer feedback. */
            feedback?: string | null;
            /**
             * Format: uuid
             * @description Writeup identifier.
             */
            id: string;
            /**
             * Format: uuid
             * @description Last reviewer.
             */
            reviewer_id?: string | null;
            /** @description Stable lifecycle state. */
            state: string;
            /**
             * Format: date-time
             * @description Last update timestamp.
             */
            updated_at: string;
        };
        /**
         * @description Organizer-selectable review outcome.
         * @enum {string}
         */
        WriteupReviewStateInput: "changes_requested" | "approved" | "published";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    verify_email: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    confirm_totp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpConfirmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodesResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    start_totp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpEnrollmentResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    start_recovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryStartRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    complete_recovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryCompleteRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    current_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryResponse"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    revoke_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session ID */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_event: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_challenges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_challenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChallengeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_hints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
                /** @description Challenge ID */
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HintResponse"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    unlock_hint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
                /** @description Challenge ID */
                challenge_id: string;
                /** @description Hint ID */
                hint_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HintUnlockResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    submit_answer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
                /** @description Challenge ID */
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    submit_survey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
                /** @description Challenge ID */
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitSurveyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    survey_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
                /** @description Challenge ID */
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveySummaryResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_writeup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
                /** @description Challenge ID */
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteupResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    save_writeup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
                /** @description Challenge ID */
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveWriteupRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteupResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    manual_review_queue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualReviewResponse"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    review_manual_submission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
                /** @description Submission ID */
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewManualSubmissionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    scoreboard: {
        parameters: {
            query?: {
                /** @description Limit rows to a division. */
                division_id?: string | null;
            };
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreboardResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_scoreboard_controls: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScoreboardControlsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_event_state: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventStateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_writeups: {
        parameters: {
            query?: {
                /** @description Stable writeup lifecycle key. */
                state?: string | null;
            };
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteupResponse"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    review_writeup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID */
                event_id: string;
                /** @description Writeup ID */
                writeup_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewWriteupRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteupResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    setup_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_teams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_team: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTeamResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    join_team: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinTeamRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    transfer_captain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferCaptainRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
