-- Kitsune's authoritative PostgreSQL schema. IDs are UUIDv7 generated by the
-- application. Secrets are encrypted or one-way-derived before persistence.

CREATE TABLE organizations (
    id uuid PRIMARY KEY,
    name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 120),
    slug text NOT NULL CHECK (slug ~ '^[a-z0-9][a-z0-9-]{0,62}$'),
    created_at timestamptz NOT NULL,
    UNIQUE (slug)
);

CREATE TABLE organization_config (
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    key text NOT NULL,
    value jsonb NOT NULL,
    secret boolean NOT NULL DEFAULT false,
    updated_by uuid,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (organization_id, key)
);

CREATE TABLE entitlements (
    organization_id uuid PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
    capabilities jsonb NOT NULL DEFAULT '{}',
    updated_at timestamptz NOT NULL
);

CREATE TABLE users (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    email text NOT NULL,
    email_normalized text NOT NULL,
    display_name text NOT NULL CHECK (length(btrim(display_name)) BETWEEN 1 AND 80),
    password_hash text,
    email_verified boolean NOT NULL DEFAULT false,
    disabled boolean NOT NULL DEFAULT false,
    custom_fields jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    UNIQUE (organization_id, email_normalized)
);

ALTER TABLE organization_config
    ADD CONSTRAINT organization_config_updated_by_fk
    FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;

CREATE TABLE email_verifications (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_digest bytea NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL
);

CREATE TABLE account_recovery_tokens (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_digest bytea NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL
);

CREATE TABLE auth_identities (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider_kind text NOT NULL CHECK (provider_kind IN ('local','oidc','saml','webauthn')),
    provider_key text NOT NULL,
    subject text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL,
    UNIQUE (provider_key, subject)
);

CREATE TABLE webauthn_credentials (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    credential_id bytea NOT NULL UNIQUE,
    public_key bytea NOT NULL,
    sign_count bigint NOT NULL DEFAULT 0 CHECK (sign_count >= 0),
    transports text[] NOT NULL DEFAULT '{}',
    name text NOT NULL,
    created_at timestamptz NOT NULL,
    last_used_at timestamptz
);

CREATE TABLE totp_credentials (
    user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    encrypted_secret bytea NOT NULL,
    enabled_at timestamptz NOT NULL,
    last_counter bigint
);

CREATE TABLE recovery_codes (
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code_digest bytea NOT NULL,
    consumed_at timestamptz,
    PRIMARY KEY (user_id, code_digest)
);

CREATE TABLE sessions (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_digest bytea NOT NULL UNIQUE,
    csrf_digest bytea NOT NULL,
    ip_prefix inet,
    user_agent_digest bytea,
    created_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz
);
CREATE INDEX sessions_user_active_idx ON sessions(user_id, expires_at) WHERE revoked_at IS NULL;

CREATE TABLE api_tokens (
    id uuid PRIMARY KEY,
    user_id uuid REFERENCES users(id) ON DELETE CASCADE,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name text NOT NULL,
    token_digest bytea NOT NULL UNIQUE,
    scopes text[] NOT NULL,
    event_ids uuid[] NOT NULL DEFAULT '{}',
    expires_at timestamptz,
    last_used_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL
);

CREATE TABLE oauth_clients (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    client_id text NOT NULL UNIQUE,
    client_secret_digest bytea NOT NULL,
    scopes text[] NOT NULL,
    disabled boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL
);

CREATE TABLE roles (
    id uuid PRIMARY KEY,
    organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
    key text NOT NULL,
    name text NOT NULL,
    permissions text[] NOT NULL,
    built_in boolean NOT NULL DEFAULT false,
    UNIQUE NULLS NOT DISTINCT (organization_id, key)
);

CREATE TABLE events (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name text NOT NULL,
    slug text NOT NULL,
    description text NOT NULL DEFAULT '',
    state text NOT NULL CHECK (state IN ('draft','scheduled','live','paused','ended','archived')),
    participation text NOT NULL CHECK (participation IN ('individual','team','hybrid')),
    modes text[] NOT NULL,
    starts_at timestamptz,
    ends_at timestamptz,
    team_size_limit smallint CHECK (team_size_limit > 0),
    scoreboard_frozen boolean NOT NULL DEFAULT false,
    scoreboard_hidden boolean NOT NULL DEFAULT false,
    freeze_at timestamptz,
    config jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at),
    UNIQUE (organization_id, slug)
);

CREATE TABLE role_grants (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    event_id uuid REFERENCES events(id) ON DELETE CASCADE,
    team_id uuid,
    granted_by uuid REFERENCES users(id) ON DELETE SET NULL,
    granted_at timestamptz NOT NULL
);
CREATE INDEX role_grants_lookup_idx ON role_grants(user_id, organization_id, event_id);

CREATE TABLE teams (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name text NOT NULL,
    invite_code_digest bytea NOT NULL,
    custom_fields jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    UNIQUE (organization_id, name)
);

ALTER TABLE role_grants
    ADD CONSTRAINT role_grants_team_fk FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;

CREATE TABLE team_members (
    team_id uuid NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    captain boolean NOT NULL DEFAULT false,
    joined_at timestamptz NOT NULL,
    PRIMARY KEY (team_id, user_id)
);
CREATE UNIQUE INDEX team_single_captain_idx ON team_members(team_id) WHERE captain;

CREATE TABLE divisions (
    id uuid PRIMARY KEY,
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    name text NOT NULL,
    position integer NOT NULL DEFAULT 0,
    UNIQUE (event_id, name)
);

CREATE TABLE brackets (
    id uuid PRIMARY KEY,
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    name text NOT NULL,
    advancement_slots smallint NOT NULL DEFAULT 0 CHECK (advancement_slots >= 0),
    config jsonb NOT NULL DEFAULT '{}',
    UNIQUE (event_id, name)
);

CREATE TABLE event_participants (
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    user_id uuid REFERENCES users(id) ON DELETE CASCADE,
    team_id uuid REFERENCES teams(id) ON DELETE CASCADE,
    division_id uuid REFERENCES divisions(id) ON DELETE SET NULL,
    bracket_id uuid REFERENCES brackets(id) ON DELETE SET NULL,
    registered_at timestamptz NOT NULL,
    CHECK ((user_id IS NOT NULL)::integer + (team_id IS NOT NULL)::integer = 1),
    UNIQUE NULLS NOT DISTINCT (event_id, user_id, team_id)
);

CREATE TABLE audiences (
    id uuid PRIMARY KEY,
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    name text NOT NULL,
    rule jsonb,
    UNIQUE (event_id, name)
);

CREATE TABLE audience_members (
    audience_id uuid NOT NULL REFERENCES audiences(id) ON DELETE CASCADE,
    user_id uuid REFERENCES users(id) ON DELETE CASCADE,
    team_id uuid REFERENCES teams(id) ON DELETE CASCADE,
    CHECK ((user_id IS NOT NULL)::integer + (team_id IS NOT NULL)::integer = 1),
    UNIQUE NULLS NOT DISTINCT (audience_id, user_id, team_id)
);

CREATE TABLE challenges (
    id uuid PRIMARY KEY,
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    name text NOT NULL,
    category text NOT NULL,
    description text NOT NULL,
    kind jsonb NOT NULL,
    state text NOT NULL CHECK (state IN ('draft','testing','scheduled','published','hidden','archived')),
    scoring jsonb NOT NULL,
    visibility jsonb NOT NULL DEFAULT '{}',
    tags text[] NOT NULL DEFAULT '{}',
    max_attempts integer CHECK (max_attempts > 0),
    writeups_enabled boolean NOT NULL DEFAULT false,
    position integer NOT NULL DEFAULT 0,
    created_by uuid REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);
CREATE INDEX challenges_board_idx ON challenges(event_id, state, category, position);

CREATE TABLE challenge_answers (
    id uuid PRIMARY KEY,
    challenge_id uuid NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
    rule jsonb NOT NULL,
    position integer NOT NULL DEFAULT 0
);

CREATE TABLE challenge_hints (
    challenge_id uuid NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
    id integer NOT NULL,
    content text NOT NULL,
    cost bigint NOT NULL DEFAULT 0 CHECK (cost >= 0),
    PRIMARY KEY (challenge_id, id)
);

CREATE TABLE hint_unlocks (
    challenge_id uuid NOT NULL,
    hint_id integer NOT NULL,
    user_id uuid REFERENCES users(id) ON DELETE CASCADE,
    team_id uuid REFERENCES teams(id) ON DELETE CASCADE,
    unlocked_at timestamptz NOT NULL,
    CHECK ((user_id IS NOT NULL)::integer + (team_id IS NOT NULL)::integer = 1),
    FOREIGN KEY (challenge_id, hint_id) REFERENCES challenge_hints(challenge_id, id) ON DELETE CASCADE,
    UNIQUE NULLS NOT DISTINCT (challenge_id, hint_id, user_id, team_id)
);

CREATE TABLE files (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    object_key text NOT NULL UNIQUE,
    filename text NOT NULL,
    content_type text NOT NULL,
    size bigint NOT NULL CHECK (size >= 0),
    sha256 text NOT NULL,
    created_by uuid REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL
);

CREATE TABLE challenge_files (
    challenge_id uuid NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
    file_id uuid NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    PRIMARY KEY (challenge_id, file_id)
);

CREATE TABLE submissions (
    id uuid PRIMARY KEY,
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    challenge_id uuid REFERENCES challenges(id) ON DELETE CASCADE,
    user_id uuid REFERENCES users(id) ON DELETE SET NULL,
    team_id uuid REFERENCES teams(id) ON DELETE SET NULL,
    outcome text NOT NULL,
    answer_digest bytea,
    checker_message text,
    idempotency_key uuid NOT NULL,
    ip_prefix inet,
    session_id uuid REFERENCES sessions(id) ON DELETE SET NULL,
    submitted_at timestamptz NOT NULL,
    reviewed_by uuid REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at timestamptz,
    CHECK ((user_id IS NOT NULL)::integer + (team_id IS NOT NULL)::integer >= 1),
    UNIQUE (event_id, idempotency_key)
);
CREATE INDEX submissions_live_ops_idx ON submissions(event_id, submitted_at DESC);
CREATE INDEX submissions_attempt_idx ON submissions(challenge_id, user_id, team_id, outcome);

CREATE TABLE challenge_solves (
    challenge_id uuid NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
    user_id uuid REFERENCES users(id) ON DELETE CASCADE,
    team_id uuid REFERENCES teams(id) ON DELETE CASCADE,
    submission_id uuid NOT NULL UNIQUE REFERENCES submissions(id) ON DELETE RESTRICT,
    solved_at timestamptz NOT NULL,
    CHECK ((user_id IS NOT NULL)::integer + (team_id IS NOT NULL)::integer = 1),
    UNIQUE NULLS NOT DISTINCT (challenge_id, user_id, team_id)
);

CREATE TABLE writeups (
    id uuid PRIMARY KEY,
    challenge_id uuid NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
    user_id uuid REFERENCES users(id) ON DELETE SET NULL,
    team_id uuid REFERENCES teams(id) ON DELETE SET NULL,
    body text NOT NULL,
    state text NOT NULL CHECK (state IN ('draft','submitted','changes_requested','approved','published')),
    reviewer_id uuid REFERENCES users(id) ON DELETE SET NULL,
    feedback text,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE survey_responses (
    id uuid PRIMARY KEY,
    challenge_id uuid NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
    user_id uuid REFERENCES users(id) ON DELETE SET NULL,
    team_id uuid REFERENCES teams(id) ON DELETE SET NULL,
    answers jsonb NOT NULL,
    submitted_at timestamptz NOT NULL
);

CREATE TABLE score_entries (
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    sequence bigint NOT NULL CHECK (sequence >= 0),
    user_id uuid REFERENCES users(id) ON DELETE SET NULL,
    team_id uuid REFERENCES teams(id) ON DELETE SET NULL,
    division_id uuid REFERENCES divisions(id) ON DELETE SET NULL,
    points bigint NOT NULL,
    reason jsonb NOT NULL,
    occurred_at timestamptz NOT NULL,
    hidden_by_freeze boolean NOT NULL DEFAULT false,
    CHECK ((user_id IS NOT NULL)::integer + (team_id IS NOT NULL)::integer = 1),
    PRIMARY KEY (event_id, sequence)
);
CREATE INDEX score_entries_board_idx ON score_entries(event_id, division_id, occurred_at);

CREATE TABLE mode_state (
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    mode_key text NOT NULL,
    version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
    state jsonb NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (event_id, mode_key)
);

CREATE TABLE instances (
    id uuid PRIMARY KEY,
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    challenge_id uuid REFERENCES challenges(id) ON DELETE CASCADE,
    team_id uuid REFERENCES teams(id) ON DELETE CASCADE,
    user_id uuid REFERENCES users(id) ON DELETE CASCADE,
    orchestrator text NOT NULL,
    provider_id text,
    template text NOT NULL,
    state text NOT NULL,
    connection jsonb,
    idempotency_key uuid NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CHECK ((user_id IS NOT NULL)::integer + (team_id IS NOT NULL)::integer >= 1)
);
CREATE INDEX instances_reaper_idx ON instances(expires_at) WHERE state NOT IN ('deleted','failed');

CREATE TABLE attack_defense_flags (
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    tick bigint NOT NULL CHECK (tick >= 0),
    service text NOT NULL,
    team_id uuid NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    flag_digest bytea NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    PRIMARY KEY (event_id, tick, service, team_id)
);

CREATE TABLE checker_results (
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    tick bigint NOT NULL CHECK (tick >= 0),
    service text NOT NULL,
    team_id uuid NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    healthy boolean NOT NULL,
    latency_ms integer CHECK (latency_ms >= 0),
    message text NOT NULL,
    checked_at timestamptz NOT NULL,
    PRIMARY KEY (event_id, tick, service, team_id)
);

CREATE TABLE notifications (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    event_id uuid REFERENCES events(id) ON DELETE CASCADE,
    recipient_user_id uuid REFERENCES users(id) ON DELETE CASCADE,
    audience_id uuid REFERENCES audiences(id) ON DELETE CASCADE,
    template text NOT NULL,
    data jsonb NOT NULL,
    priority smallint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL,
    expires_at timestamptz
);

CREATE TABLE notification_receipts (
    notification_id uuid NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    channel text NOT NULL,
    state text NOT NULL,
    delivered_at timestamptz,
    read_at timestamptz,
    error text,
    PRIMARY KEY (notification_id, user_id, channel)
);

CREATE TABLE webhooks (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name text NOT NULL,
    url text NOT NULL,
    encrypted_secret bytea NOT NULL,
    subscribed_events text[] NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL
);

CREATE TABLE webhook_deliveries (
    id uuid PRIMARY KEY,
    webhook_id uuid NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE,
    event_id uuid NOT NULL,
    attempt integer NOT NULL CHECK (attempt > 0),
    state text NOT NULL,
    response_status integer,
    response_excerpt text,
    next_attempt_at timestamptz,
    created_at timestamptz NOT NULL,
    completed_at timestamptz,
    UNIQUE (webhook_id, event_id, attempt)
);

CREATE TABLE automation_flows (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    event_id uuid REFERENCES events(id) ON DELETE CASCADE,
    name text NOT NULL,
    active_version integer,
    enabled boolean NOT NULL DEFAULT false,
    created_by uuid REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE automation_versions (
    flow_id uuid NOT NULL REFERENCES automation_flows(id) ON DELETE CASCADE,
    version integer NOT NULL CHECK (version > 0),
    graph jsonb NOT NULL,
    created_by uuid REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (flow_id, version)
);

CREATE TABLE automation_executions (
    id uuid PRIMARY KEY,
    flow_id uuid NOT NULL,
    version integer NOT NULL,
    event_envelope_id uuid NOT NULL,
    state text NOT NULL,
    node_log jsonb NOT NULL DEFAULT '[]',
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    FOREIGN KEY (flow_id, version) REFERENCES automation_versions(flow_id, version) ON DELETE CASCADE,
    UNIQUE (flow_id, version, event_envelope_id)
);

CREATE TABLE plugins (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name text NOT NULL,
    version text NOT NULL,
    source jsonb NOT NULL,
    manifest jsonb NOT NULL,
    artifact_sha256 text NOT NULL,
    signature jsonb NOT NULL,
    grants jsonb NOT NULL DEFAULT '{}',
    enabled boolean NOT NULL DEFAULT false,
    installed_at timestamptz NOT NULL,
    UNIQUE (organization_id, name)
);

CREATE TABLE plugin_state (
    plugin_id uuid NOT NULL REFERENCES plugins(id) ON DELETE CASCADE,
    namespace text NOT NULL,
    key text NOT NULL,
    value bytea NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (plugin_id, namespace, key)
);

CREATE TABLE audit_log (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    event_id uuid REFERENCES events(id) ON DELETE SET NULL,
    actor_id uuid REFERENCES users(id) ON DELETE SET NULL,
    action text NOT NULL,
    resource_type text NOT NULL,
    resource_id text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}',
    correlation_id uuid NOT NULL,
    occurred_at timestamptz NOT NULL
);
CREATE INDEX audit_log_org_time_idx ON audit_log(organization_id, occurred_at DESC, id);

CREATE TABLE command_receipts (
    idempotency_key uuid PRIMARY KEY,
    kind text NOT NULL,
    payload_sha256 bytea NOT NULL,
    aggregate_version bigint NOT NULL CHECK (aggregate_version >= 0),
    response jsonb NOT NULL,
    created_at timestamptz NOT NULL
);

CREATE TABLE event_outbox (
    id uuid PRIMARY KEY,
    organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
    event_id uuid REFERENCES events(id) ON DELETE CASCADE,
    kind text NOT NULL,
    envelope jsonb NOT NULL,
    occurred_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL
);
CREATE INDEX event_outbox_delivery_idx ON event_outbox(created_at, id);

CREATE TABLE event_deliveries (
    event_id uuid NOT NULL REFERENCES event_outbox(id) ON DELETE CASCADE,
    consumer text NOT NULL,
    delivered_at timestamptz NOT NULL,
    PRIMARY KEY (event_id, consumer)
);
